import type { Metadata } from "next";
import "./[lang]/globals.css";
import "@fontsource-variable/ibm-plex-sans";
import Providers from "./providers";

const FAVICON_PNG = "/favicon.png?v=1";
const FAVICON_ICO = "/favicon.ico?v=1";

export const metadata: Metadata = {
  title: "Fazl Admin",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: FAVICON_PNG, type: "image/png" },
      { url: FAVICON_ICO, type: "image/x-icon" },
    ],
    shortcut: FAVICON_ICO,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="font-plex" lang="en" dir="ltr" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
